[build]
  command = "node build-config.cjs"
  publish = "dist"
  environment = { SECRETS_SCAN_ENABLED = "false" }
  base = "netlify-site"

[[headers]]
  for = "/config.js"
  [headers.values]
    Cache-Control = "no-store"
